# Define the target servers for hardening and compliance checks
[servers]
172.16.89.131

# Connection variables for the 'servers' group
[servers:vars]
ansible_user=fogadmin
ansible_become=yes
ansible_become_method=sudo
