---
# hardening/roles/firewall/tasks/main.yml

- name: Garantir que o pacote UFW (Firewall) está instalado
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Permitir tráfego SSH (Crítico para não perdermos acesso!)
  ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Ativar a Firewall e negar tráfego de entrada por defeito (Default Deny)
  ufw:
    state: enabled
    direction: incoming
    policy: deny
